language: ruby
bundler_args: --without development --without assets
rvm:
  - 1.8.7
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
notifications:
  recipients:
    - awilcox@wilcox-tech.com
branches:
  only:
    - master
script:
  - RAILS_ENV="test" bundle exec rake --trace db:migrate spec
